package Vistas;

import Controlador.CRUDProveedores;
import Modelo.POJOProveedores;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class GestionarProveedor extends javax.swing.JInternalFrame {

        int datoSeleccionado2 = -1;
        
    public GestionarProveedor() {
        initComponents();
        botonmostrar.setVisible(false);
    }
    
    
     public void mostrar(){//Método mostrar 
        try {
            DefaultTableModel modelo;
                CRUDProveedores prod = new CRUDProveedores();//objeto de la clase CRUDProveedores
                modelo = prod.MostrarProveedores();
                TableProve.setModel(modelo);
                
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
     }
        public void BuscarProveedores() {
        try {
            DefaultTableModel modelo;
            CRUDProveedores pro = new CRUDProveedores();
            modelo = pro.BuscarDatos(BuscarProv.getText());
            TableProve.setModel(modelo);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }

     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        botonmostrar = new javax.swing.JButton();
        BuscarProv = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProve = new javax.swing.JTable();
        botonmostrar1 = new javax.swing.JButton();

        setClosable(true);

        jPan.setBackground(new java.awt.Color(156, 162, 239));
        jPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión de Proveedores");
        jPan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 64, -1, 41));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/basura.png"))); // NOI18N
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPan.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 40, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Variedades JuliesK");
        jPan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 32, -1, 26));

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lapiz.png"))); // NOI18N
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPan.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 40, 40));

        botonmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmostrarActionPerformed(evt);
            }
        });
        jPan.add(botonmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 54, 0, 30));

        BuscarProv.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        BuscarProv.setForeground(new java.awt.Color(153, 153, 153));
        BuscarProv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BuscarProv.setText("Buscar por ID, Nombres o Apellidos");
        BuscarProv.setBorder(null);
        BuscarProv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscarProvFocusLost(evt);
            }
        });
        BuscarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProvMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarProvMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BuscarProvMouseReleased(evt);
            }
        });
        BuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProvActionPerformed(evt);
            }
        });
        BuscarProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarProvKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarProvKeyTyped(evt);
            }
        });
        jPan.add(BuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 538, 40));

        TableProve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idProveedor", "Nombre", "Apellido", "NombreEmpresa", "Telefono"
            }
        ));
        TableProve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProveMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableProve);

        jPan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 200, 720, 300));

        botonmostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmostrar1ActionPerformed(evt);
            }
        });
        jPan.add(botonmostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 90, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPan, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Proveedor prov = new Proveedor();
        if (datoSeleccionado2 >= 0) {
            String dato = String.valueOf(TableProve.getValueAt(datoSeleccionado2, 0));
            CRUDProveedores prove = new CRUDProveedores();
            if (JOptionPane.showConfirmDialog(rootPane,
                    "Se eliminará el registro, ¿desea continuar?",
                    "Eliminar Registro",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                prove.eliminar(dato);
                mostrar();
                JOptionPane.showMessageDialog(null,
                        "Dato eliminado correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar un registro de la tabla");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

                Proveedor Prov = new Proveedor();
                int x = (MenuPrincipal.deskPane.getWidth() / 2) - Prov.getWidth() / 2;
                int y = (MenuPrincipal.deskPane.getHeight() / 2) - Prov.getHeight() / 2;
                Prov.setLocation(x, y);
                MenuPrincipal.deskPane.add(Prov);

                if (datoSeleccionado2 >= 1){
                        //mandar datos al formulario
            
                        Proveedor.NombreProv.setText(String.valueOf(TableProve.getValueAt(datoSeleccionado2, 1)));
                        Proveedor.ApellidoProv.setText(String.valueOf(TableProve.getValueAt(datoSeleccionado2, 2)));
                        Proveedor.NEmpresa.setText(String.valueOf(TableProve.getValueAt(datoSeleccionado2, 3)));
                        Proveedor.NTelefono.setText(String.valueOf(TableProve.getValueAt(datoSeleccionado2, 4)));
                        Proveedor.NombreProv.enable(false);
                        //hacer al frente y visible
                        Proveedor vista = new Proveedor();
                        vista.setVisible(true);
                        
                        prov.toFront();
                        Proveedor.GuardarProv.setVisible(true);
            prov.setVisible(true);
                        
            
                    }else{
                        JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a actualizar");
                    }
    }//GEN-LAST:event_btEditarActionPerformed

    private void botonmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmostrarActionPerformed
                mostrar();
    }//GEN-LAST:event_botonmostrarActionPerformed

    private void BuscarProvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarProvFocusLost
        //        tsProv.setText("Buscar por cédula, nombres o apellidos");
        //        tsProv.setForeground(Color.gray);
    }//GEN-LAST:event_BuscarProvFocusLost

    private void BuscarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProvMouseClicked
        BuscarProv.setText("");
    }//GEN-LAST:event_BuscarProvMouseClicked

    private void BuscarProvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProvMousePressed
        //        tsProv.setText("");
        //        tsProv.setForeground(Color.black);
    }//GEN-LAST:event_BuscarProvMousePressed

    private void BuscarProvMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProvMouseReleased

    }//GEN-LAST:event_BuscarProvMouseReleased

    private void BuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarProvActionPerformed

    private void BuscarProvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarProvKeyReleased
        BuscarProveedores();
    }//GEN-LAST:event_BuscarProvKeyReleased

    private void BuscarProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarProvKeyTyped

    }//GEN-LAST:event_BuscarProvKeyTyped

    private void TableProveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProveMouseClicked
         datoSeleccionado2 = TableProve.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_TableProveMouseClicked

    private void botonmostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmostrar1ActionPerformed
        mostrar();
    }//GEN-LAST:event_botonmostrar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarProv;
    private javax.swing.JTable TableProve;
    public static javax.swing.JButton botonmostrar;
    public static javax.swing.JButton botonmostrar1;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPan;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
