package Vistas;

import Controlador.CRUDProducto;
import Modelo.POJOCategoria;
import Modelo.POJOProducto;
import static Vistas.MenuPrincipal.deskPane;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
//        llenarCategoria();
    }
    
//     public void llenarCategoria() {
//        CRUDProducto cate = new CRUDProducto();
//        ArrayList<POJOCategoria> listaCategoria = cate.mostrarDatosCombo();
//        comboCategoria.removeAllItems();
//        for (int i = 0; i < listaCategoria.size(); i++) {
//            comboCategoria.addItem(new POJOCategoria(
//                    listaCategoria.get(i).getIDCategoria(),
//                    listaCategoria.get(i).getNombre()));
//        }
//     }
     public void guardarProducto() {
        CRUDProducto cp = new CRUDProducto();
//        // Obtener el ID de la categoría seleccionada del JComboBox
        POJOCategoria categoriaSeleccionada = (POJOCategoria) comboCategoria.getSelectedItem();
        int ID_Categoria = categoriaSeleccionada.getIDCategoria();
        
        POJOProducto p1 = new POJOProducto(NombreProducto.getText(),
                Integer.parseInt(pVenta.getText()),
                Integer.parseInt(PCompra.getText()),
                Descripcion.getText(),
                Marca.getSelectedItem(),
                Talla.getText(),
                Integer.parseInt(CantidadDisponible.getText()));
//                Integer.parseInt(Categoria.getText()));



        cp.Guardar(p1);

    }
     public boolean verificarDatos(String dato) {
        ResultSet rs;
        return verificarDatos(dato);
    }

    public void limpiar() {
        NombreProducto.setText("");
        Descripcion.setText("");
        PCompra.setText("");
//        Marca.setText("");
        Talla.setText("");
        pVenta.setText("");
        CantidadDisponible.setText("");

    }

    public void editarPro() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreProducto = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        GuardarProductos = new javax.swing.JButton();
        Talla = new javax.swing.JTextField();
        PCompra = new javax.swing.JFormattedTextField();
        pVenta = new javax.swing.JFormattedTextField();
        CantidadDisponible = new javax.swing.JFormattedTextField();
        btnAgregarCate = new javax.swing.JButton();
        botorefrescar = new javax.swing.JButton();
        cCategoria = new javax.swing.JComboBox<>();
        cCategoria1 = new javax.swing.JComboBox<>();
        btnAgregarCate1 = new javax.swing.JButton();
        botorefrescar1 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpane.setBackground(new java.awt.Color(156, 162, 239));
        jdpane.setPreferredSize(new java.awt.Dimension(620, 520));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Registrar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo Producto");

        NombreProducto.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        NombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Nombre producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        NombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProductoActionPerformed(evt);
            }
        });
        NombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreProductoKeyTyped(evt);
            }
        });

        Descripcion.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Descripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Descripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DescripcionKeyTyped(evt);
            }
        });

        GuardarProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GuardarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar.png"))); // NOI18N
        GuardarProductos.setText("Guardar");
        GuardarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProductosActionPerformed(evt);
            }
        });

        Talla.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Talla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Talla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Talla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        Talla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TallaKeyTyped(evt);
            }
        });

        PCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Precio Compra"));
        try {
            PCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        pVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Precio Venta"));
        try {
            pVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        CantidadDisponible.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), "Cantidad"));
        try {
            CantidadDisponible.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAgregarCate.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnAgregarCate.setText("+");
        btnAgregarCate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCate.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAgregarCate.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAgregarCate.setOpaque(true);
        btnAgregarCate.setPreferredSize(new java.awt.Dimension(45, 40));
        btnAgregarCate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCateMouseClicked(evt);
            }
        });
        btnAgregarCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCateActionPerformed(evt);
            }
        });

        botorefrescar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botorefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/girar.png"))); // NOI18N
        botorefrescar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botorefrescar.setMaximumSize(new java.awt.Dimension(40, 40));
        botorefrescar.setMinimumSize(new java.awt.Dimension(40, 40));
        botorefrescar.setOpaque(true);
        botorefrescar.setPreferredSize(new java.awt.Dimension(45, 40));
        botorefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botorefrescarMouseClicked(evt);
            }
        });
        botorefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botorefrescarActionPerformed(evt);
            }
        });

        cCategoria.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categorias"));
        cCategoria.setPreferredSize(new java.awt.Dimension(250, 40));
        cCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cCategoriaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cCategoriaMousePressed(evt);
            }
        });
        cCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCategoriaActionPerformed(evt);
            }
        });

        cCategoria1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cCategoria1.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcas"));
        cCategoria1.setPreferredSize(new java.awt.Dimension(250, 40));
        cCategoria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cCategoria1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cCategoria1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cCategoria1MousePressed(evt);
            }
        });
        cCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCategoria1ActionPerformed(evt);
            }
        });

        btnAgregarCate1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnAgregarCate1.setText("+");
        btnAgregarCate1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCate1.setMaximumSize(new java.awt.Dimension(40, 40));
        btnAgregarCate1.setMinimumSize(new java.awt.Dimension(40, 40));
        btnAgregarCate1.setOpaque(true);
        btnAgregarCate1.setPreferredSize(new java.awt.Dimension(45, 40));
        btnAgregarCate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCate1MouseClicked(evt);
            }
        });
        btnAgregarCate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCate1ActionPerformed(evt);
            }
        });

        botorefrescar1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        botorefrescar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/girar.png"))); // NOI18N
        botorefrescar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botorefrescar1.setMaximumSize(new java.awt.Dimension(40, 40));
        botorefrescar1.setMinimumSize(new java.awt.Dimension(40, 40));
        botorefrescar1.setOpaque(true);
        botorefrescar1.setPreferredSize(new java.awt.Dimension(45, 40));
        botorefrescar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botorefrescar1MouseClicked(evt);
            }
        });
        botorefrescar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botorefrescar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdpaneLayout = new javax.swing.GroupLayout(jdpane);
        jdpane.setLayout(jdpaneLayout);
        jdpaneLayout.setHorizontalGroup(
            jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpaneLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdpaneLayout.createSequentialGroup()
                        .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(PCompra))
                        .addGap(32, 32, 32)
                        .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(Talla)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpaneLayout.createSequentialGroup()
                        .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pVenta)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpaneLayout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(btnAgregarCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botorefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpaneLayout.createSequentialGroup()
                                .addComponent(btnAgregarCate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botorefrescar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CantidadDisponible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(jdpaneLayout.createSequentialGroup()
                .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpaneLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jdpaneLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(GuardarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdpaneLayout.setVerticalGroup(
            jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Talla))
                .addGap(37, 37, 37)
                .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(CantidadDisponible))
                .addGap(26, 26, 26)
                .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botorefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botorefrescar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(GuardarProductos)
                .addGap(282, 282, 282))
        );

        getContentPane().add(jdpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TallaKeyTyped
        //        char car = evt.getKeyChar();
        //        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            //            && car != 'á' //Minúsculas
            //            && car != 'é'
            //            && car != 'í'
            //            && car != 'ó'
            //            && car != 'ú'
            //            && car != 'Á' //Mayúsculas
            //            && car != 'É'
            //            && car != 'Í'
            //            && car != 'Ó'
            //            && car != 'Ú'
            //            && car != 'Ü'
            //            && car != 'ü'
            //            && car != 'Ñ'
            //            && car != 'ñ'
            //            && (car != (char) KeyEvent.VK_SPACE)) {
            //            evt.consume();
            //        }
    }//GEN-LAST:event_TallaKeyTyped

    private void GuardarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProductosActionPerformed
        CRUDProducto cp = new CRUDProducto();
        try {
            if ((NombreProducto.getText().equals(""))
                || (pVenta.getText().equals(""))
                || (PCompra.getText().equals(""))
                || (Descripcion.getText().equals(""))
                || (Marca.getText().equals(""))
                || (Talla.getText().equals(""))
                || (CantidadDisponible.getText().equals(""))){
                JOptionPane.showMessageDialog(null, "Tiene datos vacios");
            } else {
                    guardarProducto();
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
                    //                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "error: " + e);
        }
    }//GEN-LAST:event_GuardarProductosActionPerformed

    private void DescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescripcionKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            && car != 'á' //Minúsculas
            && car != 'é'
            && car != 'í'
            && car != 'ó'
            && car != 'ú'
            && car != 'Á' //Mayúsculas
            && car != 'É'
            && car != 'Í'
            && car != 'Ó'
            && car != 'Ú'
            && car != 'Ü'
            && car != 'ü'
            && car != 'Ñ'
            && car != 'ñ'
            && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_DescripcionKeyTyped

    private void NombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreProductoKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
            && car != 'á' //Minúsculas
            && car != 'é'
            && car != 'í'
            && car != 'ó'
            && car != 'ú'
            && car != 'Á' //Mayúsculas
            && car != 'É'
            && car != 'Í'
            && car != 'Ó'
            && car != 'Ú'
            && car != 'Ü'
            && car != 'ü'
            && car != 'Ñ'
            && car != 'ñ'
            && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreProductoKeyTyped

    private void NombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProductoActionPerformed
//     char car = evt.getKeyChar();
//        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
//            && car != 'á' //Minúsculas
//            && car != 'é'
//            && car != 'í'
//            && car != 'ó'
//            && car != 'ú'
//            && car != 'Á' //Mayúsculas
//            && car != 'É'
//            && car != 'Í'
//            && car != 'Ó'
//            && car != 'Ú'
//            && car != 'Ü'
//            && car != 'ü'
//            && car != 'Ñ'
//            && car != 'ñ'
//            && (car != (char) KeyEvent.VK_SPACE)) {
//            evt.consume();
//        }
    }//GEN-LAST:event_NombreProductoActionPerformed

    private void btnAgregarCateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCateMouseClicked
        
    }//GEN-LAST:event_btnAgregarCateMouseClicked

    private void btnAgregarCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCateActionPerformed

        AgregarCategoria ac = new AgregarCategoria();
        int x = (deskPane.getWidth() / 2) - ac.getWidth() / 2;
        int y = ((deskPane.getHeight() / 2) - ac.getHeight() / 2) - 10;
        ac.setLocation(x, y);
        deskPane.add(ac);
        ac.show();
    }//GEN-LAST:event_btnAgregarCateActionPerformed

    private void botorefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botorefrescarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botorefrescarMouseClicked

    private void botorefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botorefrescarActionPerformed
//        llenarcomboboxCategoria();
    }//GEN-LAST:event_botorefrescarActionPerformed

    private void cCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoriaMouseClicked

    private void cCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCategoriaMouseEntered
        // TODO add your handling code here:
        //        llenarcombobox();
    }//GEN-LAST:event_cCategoriaMouseEntered

    private void cCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCategoriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoriaMousePressed

    private void cCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoriaActionPerformed

    private void cCategoria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCategoria1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoria1MouseClicked

    private void cCategoria1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCategoria1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoria1MouseEntered

    private void cCategoria1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCategoria1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoria1MousePressed

    private void cCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCategoria1ActionPerformed

    private void btnAgregarCate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCate1MouseClicked

    private void btnAgregarCate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCate1ActionPerformed

    private void botorefrescar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botorefrescar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botorefrescar1MouseClicked

    private void botorefrescar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botorefrescar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botorefrescar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CantidadDisponible;
    public static javax.swing.JTextField Descripcion;
    public static javax.swing.JButton GuardarProductos;
    public static javax.swing.JTextField NombreProducto;
    private javax.swing.JFormattedTextField PCompra;
    public static javax.swing.JTextField Talla;
    public static javax.swing.JButton botorefrescar;
    public static javax.swing.JButton botorefrescar1;
    public static javax.swing.JButton btnAgregarCate;
    public static javax.swing.JButton btnAgregarCate1;
    private javax.swing.JComboBox<Categoria> cCategoria;
    private javax.swing.JComboBox<Categoria> cCategoria1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jdpane;
    private javax.swing.JFormattedTextField pVenta;
    // End of variables declaration//GEN-END:variables
}
